configuration:
  name : Munish
  age : 32

app:
  name : Spring Boot POC
  log.tomcat-version : true

server:
  port: ${port:8080}
  datasource:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost/test

---

spring:
    profiles: dev
server:
  port: ${port:8080}


---

spring:
      profiles: cloud
server:
      port: 80


---

spring:
    profiles: munish
server:
  port: ${port:8080}